name: Run Tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Run test
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
          cache: yarn
      - run: yarn install --immutable
      - run: yarn run test
